# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: cluster-ops

schedule: '*/30 1 * * *'

storage:
  size: 100Gi
  classname: gp2
  pvc: roxctl-backup-pvc
  accessmodes: ReadWriteOnce

serviceaccount: roxctl-backup-user
