kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.pvc }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.classname }}
  volumeMode: Filesystem
---
